In [1]:
import numpy as np

In [11]:
b1 = np.ones(10)
b1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# 연습문제 1. 길이가 10인 0-벡터를 만드세요

In [10]:
a1 = np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
### 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드시오

In [6]:
np.r_[np.zeros(4),np.ones(1),np.zeros(4)]

array([0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [13]:
### 10부터 49까지의 값을 가지는 벡터를 만드세요.
a2 = np.arange(10,50)
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [41]:
### 위(3번) 벡터의 순서를 바꾸세요
aa = a2[::-1]
print(aa)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [47]:
aat = np.flip(a2)
aat

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [50]:
aat1 = np.flip(a2, axis=0)
aat1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [18]:
### 0부터 8까지의 값을 가지는 3X3 행렬을 만드세요
a3 = np.array([[0,1,2],[3,4,5],[6,7,8]])
a3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
### 벡터 [1,2,0,0,4,0]에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요
a4 = np.array([[1,2,0,0,4,0]])
a4[a4>0]

array([1, 2, 4])

In [31]:
### 3X3단위 행렬(indentity matrix)을 만드세요
a5 = np.identity(n=3)
a5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
### 난수 원소를 가지는 3X3 행렬을 만드세요
y = np.random.rand(3,3)
y

array([[0.23612501, 0.84410886, 0.77922374],
       [0.49825027, 0.78162876, 0.02080242],
       [0.94521074, 0.34612384, 0.41654488]])

In [38]:
### 위 (8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요
y.argmax(), y.argmin()

(6, 5)

In [40]:
### 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요
y.mean(axis=1), y.mean(axis=0)

(array([0.6198192 , 0.43356049, 0.56929315]),
 array([0.55986201, 0.65728716, 0.40552368]))