# Numpy

### Numpy array

In [1]:
### 리스트와 넘파이 어레이 속도 비교
import numpy as np 
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

In [2]:
%%time # %%:매직 명령어, 셀이 돌아가는 시간을 알려줌
for i in range(100):
    sum(nu_list)

Wall time: 160 ms


In [3]:
%%time
for i in range(100):
    sum = 0
    np.sum(np_arr)

Wall time: 5 ms


### 1차원 배열 만들기

### array
-  array 함수에 리스트를 넣으면 ndarray 클래스 객체 즉, 배열로 변환

In [4]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)

numpy.ndarray

### shape
- shape 속성은 배열의 크기를 반환

In [6]:
ar.shape # (10,)은 1차원 ,다음에 숫자가 하나 더오면 2차원

(10,)

In [7]:
al = [2*i for i in range(10)]
al

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
2 * ar #한번에 두배화를 간단하게 할수있는것이 벡터화

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
al * 2 # 벡터화는 리스트에서 가능하지 않음

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [11]:
2 * a + b

array([12, 24, 36])

In [12]:
a == 2

array([False,  True, False])

In [13]:
b > 15

array([False,  True,  True])

In [14]:
(a == 2) & (b > 10)

array([False,  True, False])

### 2차월 매열 만들기

In [15]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
c.shape # 행이 2개 열이 3개

(2, 3)

In [17]:
len(c), len(c[0])

(2, 3)

In [18]:
d = np.array([[10,20,30,40], [50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [19]:
d.shape

(2, 4)

In [20]:
np.arange(10, 90, 10).reshape(2,-1) 

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 3차원 배열 만들기

In [21]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [22]:
d.shape

(2, 3, 4)

In [23]:
d.shape, d.ndim

((2, 3, 4), 3)

### 배열의 인덱싱

In [24]:
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [25]:
a[-1]

4

In [26]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a[1, 0]

3

### 배열 슬라이싱

In [27]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
a[:, 1:3]

array([[1, 2],
       [5, 6]])

In [29]:
# 연습 문제 2
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [30]:
# 이 행렬에서 값 7 을 인덱싱한다
m[1,2]

7

In [31]:
# 이 행렬에서 값 14 을 인덱싱한다.
m[2,-1]

14

In [32]:
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다
m[1:2,1:3]

array([[6, 7]])

In [48]:
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다
m[1:,2:3]

array([[ 7],
       [12]])

In [49]:
#이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2,3:] 

array([[3, 4],
       [8, 9]])

In [34]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx] #값이 True만 출력

array([0, 2, 4, 6, 8])

In [35]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [36]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [37]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [38]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [39]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
a[:, [True, False, False, True]] #열은 전부다

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [41]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [42]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [44]:
x[x % 4==1]

array([ 1,  5,  9, 13, 17])

In [45]:
x[[x % 3 == 0] and [x % 4== 1]]

array([ 1,  5,  9, 13, 17])