# 배열의 생성과 변형

In [22]:
import numpy as np

### 넘파이의 자료형

In [23]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [24]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [25]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [26]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [27]:
x = np.array([1, 2, 3], dtype='float32') #반정도 부동 소수자
x.dtype

dtype('float32')

### Inf와 NaN

In [28]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

In [29]:
np.log(0)

-inf

In [30]:
np.exp(-np.inf)

0.0

### 배열 생성

In [31]:
a = np.zeros(5) # zeros: 크기가 정해져 있고 모든 값이 0인 배열을 생성
a

array([0., 0., 0., 0., 0.])

In [32]:
a.dtype #기본이 실수

dtype('float64')

In [33]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
c = np.zeros((5, 2), dtype="int") # dtype을 잡아서 주면 됨 불이연은 폴스
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [35]:
c.dtype

dtype('int32')

In [36]:
np.ones(4) # ones :0이 아닌 1로 초기화된 배열을 생성

array([1., 1., 1., 1.])

In [37]:
np.ones_like(b) #쉐입과 같은 타입으로 원을 채워넣어라?

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### arange

In [39]:
# arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있다. 특정한 규칙에 따라 증가하는 수열을 만든다

In [40]:
np.arange(10)  # 0 .. n-1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계(증분)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

### linspace 과 logspace

In [42]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할

In [43]:
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [44]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [45]:
np.log(np.logspace(0.1, 1, 10))

array([0.23025851, 0.46051702, 0.69077553, 0.92103404, 1.15129255,
       1.38155106, 1.61180957, 1.84206807, 2.07232658, 2.30258509])

### 전치 연산

In [46]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
A.T # 행과 열을 바꿈

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
A.T @ A

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [49]:
A @ A.T

array([[14, 32],
       [32, 77]])

### 배열의 크기 변형

In [50]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### reshape
- 내부 데이터는 보존한 채로 형태만 바꾸려면 reshape 

In [51]:
b = a.reshape(3, 4) # 행의 갯수 , 열의 갯수
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a.reshape(3, -1) # -1는 갯수를 맞춰서 알아서 꽉 채우라는 뜻

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a.reshape(3, 2, -1)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

### flatten
- 다차원 배열을 무조건 1차원으로 만들기

In [55]:
b.flatten() #다시 1차원으로 펼쳐짐

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [58]:
x.reshape(1, -1)

array([[0, 1, 2, 3, 4]])

In [59]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

### newaxis

In [60]:
x[:, np.newaxis] #차원만 1차원 증가

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 배열 연결

In [61]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [63]:
### hstack :행의 수가 같은 두 개 이상의 배열을 옆으로 연결

In [64]:
np.hstack([a1, a2]) # a1옆에 a2를 쌓으라는 것

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [65]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
### vstack : 열의 수가 같은 두 개 이상의 배열을 위아래로 연결
### 행열을 위아래로 쌓는것 주의는 사이즈가 어떤게 같은가에 따라 hstack과 vstack 선택

In [68]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
# 연습문제 3.2.1
a3 = np.ones((3, 2))
a3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
x = np.array([[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]])
x

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [75]:
b3 = np.hstack([b2, a3])
b3

array([[0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 2차원 그리드 포인트 생성

In [60]:
x = np.arange(3) # 격자점
x

array([0, 1, 2])

In [61]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [62]:
X, Y = np.meshgrid(x, y)

In [64]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [65]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [66]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [ ]:
### 