## 난수 발생과 카운팅

In [1]:
import numpy as np

### 시드(seed) 설정하기

In [ ]:
### rand 함수는 0과 1사이의 난수를 발생시키는 함수로 인수로 받은 숫자 횟수만큼 난수를 발생

In [2]:
np.random.rand(5)

array([0.9302179 , 0.46999824, 0.13334611, 0.73979662, 0.73492366])

In [3]:
np.random.rand(5)

array([0.96766344, 0.85509074, 0.42803818, 0.14161722, 0.68901268])

In [4]:
np.random.seed(2020) # 시드값을 주면 값이 동일
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [5]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

### 데이터의 순서 바꾸기

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.shuffle(x) # 안에 있는 데이터를 무자위로 섞는것
x

array([5, 7, 6, 4, 3, 1, 2, 8, 9, 0])

### 데이터 샘플링

In [9]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다. replace가 F이면 비복원

array([4, 0, 1, 2, 3])

In [11]:
np.random.choice(5, 5, replace=True)

array([4, 4, 0, 4, 1])

In [13]:
np.random.choice(5, 3, replace=False) # 3개만 선택

array([0, 3, 4])

In [14]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  
# 선택 확률을 다르게 해서 10개 선택

array([3, 2, 2, 2, 3, 2, 3, 2, 0, 3])

### 난수(random) 생성
- rand: 0부터 1사이의 균일 분포
- randn: 표준 정규 분포 :함수는 기댓값이 0이고 표준편차가 1인 표준 정규 분포를 따르는 난수를 생성
- randint: 균일 분포의 정수 난수 :
함수는 다음과 같은 인수를 가진다 
- numpy.random.randint(low, high=None, size=None)

In [16]:
np.random.rand(5) #유니폼 0~5까지 확률이 일정

array([0.32579935, 0.86519536, 0.91088451, 0.9124617 , 0.33732149])

In [17]:
np.random.randn(10) #randn 표준정규분포

array([-0.12015076, -0.48352493,  0.53825049,  1.23793055,  0.14021035,
        1.38925737,  0.18708701,  0.45131922,  1.80806884, -0.51693141])

In [18]:
np.random.randint(10, size=10) #최대값 10 그중에 10를 찾아라

array([7, 7, 2, 5, 0, 0, 8, 3, 6, 3])

In [19]:
np.random.randint(10, 20, size=10) #10~20까지 그중에 10개를 찾아라

array([14, 16, 19, 15, 12, 14, 13, 10, 19, 18])

In [22]:
# 연습문제 : 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

x = np.random.randn(250) * 100 + 10000
x[:10]

array([ 9881.15227947, 10043.97788541, 10161.24924465,  9867.10130126,
        9996.50119782,  9997.71399001,  9917.24931613, 10143.9601829 ,
        9983.29304986,  9926.22920754])

In [25]:
price = 10000
tomorrow = price * (1+np.random.randn(1)/100.)
tomorrow[0]

9956.828689008473

In [26]:
prices = []
price = 10000
for i in range(250):
    tmp = price * (1 + np.random.randn(1)/100.)
    price = tmp[0]
    prices.append(price)
prices[:10]

[9828.337253276753,
 9950.731082244758,
 10088.076493723946,
 9982.275659013532,
 10015.31812863973,
 10058.78505308395,
 10180.031362644377,
 10340.23062250135,
 10237.65111040987,
 10230.37018715903]

### 정수 데이터 카운팅

In [28]:
### unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [29]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True) # 문자일경우는 index, count

In [31]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [32]:
count

array([2, 2, 1], dtype=int64)

In [33]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6) # 빈 카운트: 없는 것을 표시해줌

array([0, 2, 3, 1, 0, 0], dtype=int64)