### 벡터와 벡터의 곱셈

In [3]:
import numpy as np

In [6]:
x = np.arange(1,4).reshape(3,1)
x

array([[1],
       [2],
       [3]])

In [5]:
y = np.arange(4,7).reshape(3,1)
y

array([[4],
       [5],
       [6]])

In [7]:
x.shape, y.shape

((3, 1), (3, 1))

In [8]:
x.T.shape 

(1, 3)

In [9]:
z= x.T @ y
z

array([[32]])

In [10]:
z.shape

(1, 1)

In [11]:
z[0,0] #z의 숫자하나를 가져올려면

32

In [12]:
np.dot(x.T, y)

array([[32]])

In [14]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
x @ x.T

array([[14, 32],
       [32, 77]])

In [21]:
z = np.zeros((len(x), len(y[0])), dtype = 'i')
for i in range(len(x)):
    for m in range(len(y[0])):
        val = 0
        for k in range(len(x[0])):
            val += x[i, k] * y[k, m]
        z[i,m] = val
z

array([[32],
       [77]], dtype=int32)

In [22]:
np.dot(x,y)

array([[32],
       [77]])

In [25]:
### 연습 문제 2.2.1 : A, B, C 세 회사의 주식은 각각 100만원, 80만원, 50만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하고자 한다.

#(1) 주식의 가격과 수량을 각각 p 벡터, n 벡터로 표시하고 넘파이로 코딩한다.

#(2) 주식을 매수할 때 필요한 금액을 곱셈으로 표시하고 넘파이 연산으로 그 값을 계산한다.

p = np.array([100, 80, 50]) * 10000
p = p.reshape(1, 3)

In [26]:
n = np.array([3, 4, 5]).reshape(3, 1)

In [27]:
money = (p @ n)[0, 0]
money

8700000

In [ ]:
### 연습 문제 2.2.4 (1) A와 B가 위와 같을 때 AB를 연습장에 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다.

(2) 순서를 바꾸어 BA를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. BA가 AB와 같은가?

(3) A, B가 다음과 같을 때, AB, BA를 (계산이 가능하다면) 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. AB, BA 모두 계산 가능한가?



In [28]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = A @ B
C

array([[22, 28],
       [49, 64]])